version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory 
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      CORS_ALLOW_ORIGIN: 'http://localhost:5173'
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./api/public:/srv/app/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5051:80"
    depends_on:
      - database

  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  web:
    image: node:18-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./vite-vue:/usr/local/vite-vue
    working_dir: /usr/local/vite-vue
    command: sh -c "npm install && npm run dev"