version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
      APP_DEBUG: true
      STRIPE_WEBHOOK_ENDPOINT_SECRET: whsec_KuHK0vmLz3sNVY33c3vCd9vIgBSJGMZL
      FRONT_URL: https://challenge-one-five.vercel.app/
      CORS_ALLOW_ORIGIN: '^https:\/\/challenge-one-five.vercel.app$'

  caddy:
    volumes:
      - ./api/docker/caddy/CaddyfileProd:/etc/caddy/Caddyfile:ro