# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        img:
            uri_prefix:         '%app.path.imgs%'
            upload_destination: '%kernel.project_dir%/public%app.path.imgs%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
