controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authentication_token:
    path: /authentication_token
    methods: ['POST']

payment_intent:
    path: /stripe
    methods: ['POST']